Controllers/MenagerZamowienController.cs
using KlubSosnowy.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using KlubSosnowy.Models.ViewModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KlubSosnowy.Controllers
{
    public class MenagerZamowienController : Controller
    {
        private ZamowieniaContext db = new ZamowieniaContext();
        public ActionResult Index(bool czyZrealizowane = false)
        {
            ViewBag.CzyZrealizowane = czyZrealizowane;
            return View((from xx in db.Zamowienia
                         join yy in db.Users
                         on xx.IdKlienta equals new Guid(yy.Id)
                         select new ZamowieniaKlient
                         {
                             IdZamowienia=xx.IdZamowienia,
                             IdKlienta=xx.IdKlienta,
                             NazwaKlienta=yy.UserName,
                             CzyZrealizowane=xx.CzyZrealizowane,
                             DataDodania=xx.DataDodania,
                             DataRealizacji=xx.DataRealizacji
                         }).ToList());
        }
        public ActionResult SzczegolyWszyscy(int id)
        {
            ViewBag.IdZamowienia = id;
            var lista = (from xx in db.PozycjeZamowienia
                         join yy in db.Potrawy
                         on xx.IdPotrawy equals yy.IdPotrawy
                         where xx.IdZamowienia == id
                         select new PotrawyZamowieniaViewModel
                         {
                             Cena = yy.Cena,
                             IdPotrawy = xx.IdPotrawy,
                             Ilosc = xx.Ilosc,
                             Nazwa = yy.Nazwa
                         }).ToList();
            return View(lista);
        }
        public ActionResult PokazMojeZamowienia(bool czyZrealizowane = false)
        {
            ViewBag.CzyZrealizowane = czyZrealizowane;
            if (User.Identity.GetUserId()==null)
            {
                return RedirectToAction("Login","Account");
            }
            Guid userId = new Guid(User.Identity.GetUserId());
            return View(db.Zamowienia.Where(x => x.IdKlienta == userId && x.CzyZrealizowane == czyZrealizowane).ToList());
        }
        public ActionResult Szczegoly(int id)
        {

            ViewBag.IdZamowienia = id;
            var lista = (from xx in db.PozycjeZamowienia
                         join yy in db.Potrawy
                         on xx.IdPotrawy equals yy.IdPotrawy
                         where xx.IdZamowienia == id 
                         select new PotrawyZamowieniaViewModel
                         {
                             Cena = yy.Cena,
                             IdPotrawy = xx.IdPotrawy,
                             Ilosc = xx.Ilosc,
                             Nazwa = yy.Nazwa
                         }).ToList();
            return View(lista);
        }


    }
}

Views/MenagerZamowien/Index.cshtml
@model List<KlubSosnowy.Models.ViewModel.ZamowieniaKlient>

@{
    ViewBag.Title = "Zamowione potrawy przez klientow";

}

<h2>Zamow Potrawy</h2>
@using (Html.BeginForm("PokazMojeZamowienia", "MenagerZamowien"))
{
    <center> @Html.CheckBox("Zrealizowane", (bool)ViewBag.CzyZrealizowane, new { onchange = "this.form.submit()" }) </center>
}
<table class="table">
    <tr>
        <th>
            Nazwa Klienta
        </th>
        <th>
            IdZamowienia
        </th>
        <th>
            DataZamowienia
        </th>
        <th>
            Data Realizacji
        </th>
        <th>
            Czy Zrealizowane
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.NazwaKlienta
            </td>
            <td>
                @item.IdZamowienia
            </td>
            <td>
                @item.DataDodania
            </td>
            <td>
                @item.DataRealizacji
            </td>
            <td>
                @{var czyZ = (item.CzyZrealizowane ? "Tak" : "Nie");} @Html.DisplayFor(modelItem => czyZ)
            </td>
            <td>
                <a href="@Url.Action("SzczegolyWszyscy","MenagerZamowien",new {id=item.IdZamowienia})" type="button" class="btn-primary btn">Pokaz szczegoly Zamowienia</a>
            </td>
        </tr>
    }
</table>

Views/MenagerZamowien/PokazMojeZamowienia.cshtml
@model List<KlubSosnowy.Models.Zamowienia>

@{
    ViewBag.Title = "Zamow Potrawy";

}

<h2>Zamow Potrawy</h2>
@using (Html.BeginForm("PokazMojeZamowienia", "MenagerZamowien"))
{
    <center> @Html.CheckBox("Zrealizowane", (bool)ViewBag.CzyZrealizowane, new { onchange = "this.form.submit()" }) </center>
}
    <table class="table">
        <tr>
            <th>
                IdZamowienia
            </th>
            <th>
                DataZamowienia
            </th>
            <th>
                Data Realizacji
            </th>
            <th>
                Czy Zrealizowane
            </th>
            <th>
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.IdZamowienia
                </td>
                <td>
                    @item.DataDodania
                </td>
                <td>
                    @item.DataRealizacji
                </td>
                <td>
                    @{var czyZ = (item.CzyZrealizowane ? "Tak" : "Nie");} @Html.DisplayFor(modelItem => czyZ)
                </td>
                <td>
                    <a href="@Url.Action("Szczegoly","MenagerZamowien",new {id=item.IdZamowienia})" type="button" class="btn-primary btn">Pokaz szczegoly Zamowienia</a>
                </td>
            </tr>
        }
    </table>

Views/MenagerZamowien/Szczegoly.cshtml
@model List<KlubSosnowy.Models.ViewModel.PotrawyZamowieniaViewModel>

@{
    ViewBag.Title = "Szczegoly Zamowienia";
}

<h2>Zamow nr @ViewBag.IdZamowienia</h2>
<a href="@Url.Action("PokazMojeZamowienia","MenagerZamowien")" type="button" class="btn-primary btn">Cofnij</a>
<table class="table">
    <tr>
        <th>
            IdPotrawy
        </th>
        <th>
            Nazwa
        </th>
        <th>
            Cena
        </th>
        <th>
            Ilosc
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.IdPotrawy
            </td>
            <td>
                @item.Nazwa
            </td>
            <td>
                @item.Cena
            </td>
            <td>
                @item.Ilosc
            </td>
        </tr>
    }
</table>

Views/MenagerZamowien/SzczegolyWszyscy.cshtml
@model List<KlubSosnowy.Models.ViewModel.PotrawyZamowieniaViewModel>

@{
    ViewBag.Title = "Szczegoly Zamowienia";
}

<h2>Zamowienie nr @ViewBag.IdZamowienia klienta </h2>
<a href="@Url.Action("Index","MenagerZamowien")" type="button" class="btn-primary btn">Cofnij</a>
<table class="table">
    <tr>
        <th>
            IdPotrawy
        </th>
        <th>
            Nazwa
        </th>
        <th>
            Cena
        </th>
        <th>
            Ilosc
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.IdPotrawy
            </td>
            <td>
                @item.Nazwa
            </td>
            <td>
                @item.Cena
            </td>
            <td>
                @item.Ilosc
            </td>
        </tr>
    }
</table>