Models/Potrawy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace KlubSosnowy.Models
{
    public class Potrawy
    {
        [Key]
        public int IdPotrawy { get; set; }
        public string Nazwa { get; set; }
        public decimal Cena { get; set; }
        public virtual ICollection<Potrawy_Skladniki> Potrawy_Skladniki { get; set; }
        public virtual ICollection<PozycjeZamowienia> PozycjeZamowienia { get; set; }

    }
}

Controllers/PotrawyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using MoreLinq;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KlubSosnowy.Models.ViewModel;
using KlubSosnowy.Models;

namespace KlubSosnowy.Controllers
{
    [Authorize(Roles = "Admin,Kucharz")]
    public class PotrawyController : Controller
    {
        private readonly ZamowieniaContext db = new ZamowieniaContext();
        [AllowAnonymous]
        // GET: Potrawy
        public ActionResult Index()
        {
            return View(db.Potrawy.ToList());
        }

        // GET: Potrawy/EdytujPotrawe/5
        public ActionResult EdytujPotrawe(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<PotrawySkladnikiViewModel> potrawySkladniki = (from ps in db.Potrawy_Skladniki
                                         join s in db.Skladniki
                                         on ps.IdSkladnika equals s.IdSkladnika
                                         join p in db.Potrawy
                                         on ps.IdPotrawy equals p.IdPotrawy
                                         where ps.IdPotrawy == id
                                         select new PotrawySkladnikiViewModel
                                         {
                                            IdPotrawy=ps.IdPotrawy,
                                            NazwaPotrawy=p.Nazwa,
                                            IdSkladnika=s.IdSkladnika,
                                            IdPotrawySkladnik=ps.IdPotrawy_Skladnika,
                                            NazwaSkladnika =s.Nazwa,
                                            IloscSkladnika=ps.Ilosc,
                                            JednostkaMiary=s.JednostkaMiary
                                         }).ToList();
            var potrawa = db.Potrawy.FirstOrDefault(x => x.IdPotrawy == id);
            ViewBag.NazwaPotrawy = potrawa.Nazwa;
            ViewBag.IdPotrawy = potrawa.IdPotrawy;

            if (potrawySkladniki == null)
            {
                return HttpNotFound();
            }
            return View(potrawySkladniki);
        }
        // POST:  Potrawy/EdytujPotrawe/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult EdytujPotrawe(List<Potrawy_Skladniki> potrawySkladniki)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in potrawySkladniki)
                {
                    db.Entry(item).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(potrawySkladniki);
        }

        // GET: Potrawy/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Potrawy/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPotrawy,Nazwa,Cena")] Potrawy potrawy)
        {
            if (ModelState.IsValid)
            {
                db.Potrawy.Add(potrawy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(potrawy);
        }

        // GET: Potrawy/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Potrawy potrawy = db.Potrawy.Find(id);
            if (potrawy == null)
            {
                return HttpNotFound();
            }
            return View(potrawy);
        }

        // POST: Potrawy/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPotrawy,Nazwa,Cena")] Potrawy potrawy)
        {
            if (ModelState.IsValid)
            {
                db.Entry(potrawy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(potrawy);
        }


        // GET: Potrawy/AddSkladnik/5
        public ActionResult AddSkladnik(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            List<PotrawySkladnikiViewModel> skladniki = (from sk in db.Skladniki
                                                         where !(from sp in db.Potrawy_Skladniki
                                                                 where sp.IdPotrawy==id select sp.IdSkladnika).Contains(sk.IdSkladnika)
                                                          select new PotrawySkladnikiViewModel {
                                                              IdSkladnika = sk.IdSkladnika,
                                                              NazwaSkladnika = sk.Nazwa,
                                                              JednostkaMiary = sk.JednostkaMiary
                                                          }).ToList();

            if (skladniki == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdPotrawy = id;
            return View(skladniki);
        }
        
        // POST: Potrawy/AddSkladnik/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult AddSkladnik(List<PotrawySkladnikiViewModel> potrawySkladniki)
        {
            List<Potrawy_Skladniki> potrSkladnikiConverted = (from post in potrawySkladniki
                                                              where post.IloscSkladnika !=0
                                                              select new Potrawy_Skladniki
                                           {
                                               IdPotrawy = post.IdPotrawy,
                                               IdSkladnika = post.IdSkladnika,
                                               Ilosc = post.IloscSkladnika,
                                           }).ToList();
            int idPotrawy = potrawySkladniki.FirstOrDefault().IdPotrawy;
            if (ModelState.IsValid)
            {
                foreach (var item in potrSkladnikiConverted)
                {
                    db.Entry(item).State = EntityState.Added;
                }
                db.SaveChanges();
                return RedirectToAction("EdytujPotrawe", new { id = idPotrawy });
            }
            return View(potrawySkladniki);
        }

        // GET: Potrawy/DeleteSkladnik/5
        public ActionResult DeleteSkladnik(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Potrawy_Skladniki potrawySkladniki = db.Potrawy_Skladniki.Find(id);
            if (potrawySkladniki == null)
            {
                return HttpNotFound();
            }
            return View(potrawySkladniki);
        }

        // POST: Potrawy/DeleteSkladnik/5
        [HttpPost, ActionName("DeleteSkladnik")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteSkladnikConfirmed(int id)
        {
            Potrawy_Skladniki potrawySkladniki = db.Potrawy_Skladniki.Find(id);
            db.Potrawy_Skladniki.Remove(potrawySkladniki);
            db.SaveChanges();
            return RedirectToAction("EdytujPotrawe", new { id = potrawySkladniki.IdPotrawy });
        }

        // GET: Potrawy/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Potrawy potrawy = db.Potrawy.Find(id);
            if (potrawy == null)
            {
                return HttpNotFound();
            }
            return View(potrawy);
        }

        // POST: Potrawy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Potrawy potrawy = db.Potrawy.Find(id);
            db.Potrawy.Remove(potrawy);
            IEnumerable<Potrawy_Skladniki> poSk = db.Potrawy_Skladniki.Where(x => x.IdPotrawy == id);
            foreach (var item in poSk)
            {
                db.Potrawy_Skladniki.Remove(item);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Potrawy/AddSkladnik.cshtml
@model List<KlubSosnowy.Models.ViewModel.PotrawySkladnikiViewModel>

@{
    ViewBag.Title = "Add Skladniki";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            NazwaSkladnika
        </th>
        <th>
            Ilość
        </th>
        <th>
            JednostkaMiary
        </th>
    </tr>

    @using (Html.BeginForm("AddSkladnik", "Potrawy", FormMethod.Post))
    {
        for (var i = 0; i < Model.Count(); i++)
        {
            <tr>
                <td>
                    @Html.Hidden("potrawySkladniki[" + @i + "].IdSkladnika", Model[i].IdSkladnika)
                    @Html.TextBox("potrawySkladniki[" + @i + "].NazwaSkladnika", Model[i].NazwaSkladnika, new { @readonly = "readonly" })
                </td>
                <td>
                    @Html.Hidden("potrawySkladniki[" + @i + "].IdPotrawy", (int)ViewBag.IdPotrawy)
                    @Html.TextBox("potrawySkladniki[" + @i + "].IloscSkladnika", Model[i].IloscSkladnika)
                </td>
                <td>
                    @Html.TextBox("potrawySkladniki[" + @i + "].JednostkaMiary", Model[i].JednostkaMiary, new { @readonly = "readonly" })
                </td>
            </tr>
        }
        <tr>
            <td colspan="4">
                <input type="submit" value="Submit" />
            </td>
        </tr>
    }
</table>

Views/Potrawy/Create.cshtml
@model KlubSosnowy.Models.Potrawy

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Potrawy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Potrawy/Delete.cshtml
@model KlubSosnowy.Models.Potrawy

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Potrawy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Potrawy/DeleteSkladnik.cshtml
@model KlubSosnowy.Models.Potrawy_Skladniki

@{
    ViewBag.Title = "Delete skladnik";
}

<h2>Delete Skladnik</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Potrawy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Skladniki.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skladniki.Nazwa)
        </dd>
        <dd>
            @Html.DisplayNameFor(model => model.Ilosc)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Ilosc)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Edi")
        </div>
    }
</div>

Views/Potrawy/Edit.cshtml
@model KlubSosnowy.Models.Potrawy

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Potrawy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPotrawy)

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Potrawy/EdytujPotrawe.cshtml
@model List<KlubSosnowy.Models.ViewModel.PotrawySkladnikiViewModel>

@{
    ViewBag.Title = "EdytujPotrawe";
}

<h2>EdytujPotrawe</h2>

<div>
    <h4>Skladniki dla zrobienia @ViewBag.NazwaPotrawy :</h4>
    <hr />
    <p>
        @Html.ActionLink("Dodaj skladnik", "AddSkladnik", new { id = @ViewBag.IdPotrawy })
    </p>

    <table class="table">
        <tr>
            <th>
                IdPotrawy_skladnika
            </th>
            <th>
                NazwaSkladnika
            </th>
            <th>
                IloscSkladnika
            </th>
            <th>
                JednostkaMiary
            </th>
            <th>
            </th>
        </tr>
        @using (Html.BeginForm("EdytujPotrawe", "Potrawy", FormMethod.Post))
        {
            for (var i = 0; i < Model.Count(); i++)
            {
                <tr>
                    <td>
                        @Html.Hidden("potrawySkladniki.IdPotrawy_Skladnika", @i)
                        @Html.TextBox("potrawySkladniki[" + @i + "].IdPotrawy_Skladnika", Model[i].IdPotrawySkladnik, new { @readonly = "readonly" })
                    </td>
                    <td>
                        @Html.Hidden("potrawySkladniki[" + @i + "].IdSkladnika", Model[i].IdSkladnika)
                        @Html.TextBox("potrawySkladniki[" + @i + "].NazwaSkladnika", Model[i].NazwaSkladnika, new { @readonly = "readonly" })
                    </td>
                    <td>
                        @Html.Hidden("potrawySkladniki[" + @i + "].IdPotrawy", Model[i].IdPotrawy)
                        @Html.TextBox("potrawySkladniki[" + @i + "].Ilosc", Model[i].IloscSkladnika)
                    </td>
                    <td>
                        @Html.TextBox("potrawySkladniki[" + @i + "].JednostkaMiary", Model[i].JednostkaMiary, new { @readonly = "readonly" })
                    </td>
                    <td>
                        @*@Html.ActionLink("Edytuj Skladnik", "EditSkladnik", new { id = item.IdPotrawySkladnik }) |*@
                        @*@Html.ActionLink("Details", "Details", new { id = item.IdPotrawy }) |*@
                        @*jeszcze nie gotowe trzeba wstawic usuwanie*@
                        @Html.ActionLink("Usun Skladnik", "DeleteSkladnik", new { id = Model[i].IdPotrawySkladnik })
                    </td>
                </tr>
            }
            <tr>
                <td colspan="4">
                    <input type="submit" value="Submit" />
                </td>
            </tr>
        }
    </table>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Potrawy/Index.cshtml
@model IEnumerable<KlubSosnowy.Models.Potrawy>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cena)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cena)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdPotrawy }, new { @class = "btn-primary btn" }) |
            @Html.ActionLink("EdytujPotrawe", "EdytujPotrawe", new { id=item.IdPotrawy }, new { @class = "btn-success btn" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdPotrawy }, new { @class = "btn-primary btn" })
        </td>
    </tr>
}

</table>