Models/Zamowienia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KlubSosnowy.Models
{
    public class Zamowienia
    {
        [Key]
        public int IdZamowienia { get; set; }
        public int IdKlienta { get; set; }
        public DateTime DataDodania { get; set; }
        public virtual ICollection<PozycjeZamowienia> PozycjeZamowienia { get; set; }
    }
}

Controllers/ZamowieniaController.cs
using KlubSosnowy.Models;
using KlubSosnowy.Models.ViewModel;
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using MoreLinq;
using System.Web;
using System.Web.Mvc;

namespace KlubSosnowy.Controllers
{
    public class ZamowieniaController : Controller
    {
        private readonly ZamowieniaContext db = new ZamowieniaContext();
        private const string ZamowieniaSesjaKlucz = "zamowienieSesja";

        public ZamowieniaController()
        {
            //var roleStore = new RoleStore<IdentityRole>(db);
            //var roleMenager = new RoleManager<IdentityRole>(roleStore);
            //var rolaAdmin = new IdentityRole { Name = "Kucharz" };
            //roleMenager.Create(rolaAdmin);
            //var rolaAdmin2 = new IdentityRole { Name = "Zakupowiec" };
            //roleMenager.Create(rolaAdmin2);
            //db.SaveChanges();



            //var userStore = new UserStore<ApplicationUser>(db);
            //var userManager = new UserManager<ApplicationUser>(userStore);
            //string haslo = "Sh!ft3891";
            //string email = "admin@klubsosnowy.com";
            //ApplicationUser uzytkownik = new ApplicationUser()
            //{
            //    UserName = email,
            //    Email = email,
            //    EmailConfirmed = true,
            //};
            //if (userManager.Create(uzytkownik, haslo).Succeeded)
            //{
            //    userManager.AddToRole(uzytkownik.Id, "Admin");
            //}
            //db.SaveChanges();
        }

        public ActionResult TestLinqWithViewFromSql()
        {
            int id = 2;
            var xx = db.Database.SqlQuery<string>("select * from PotrawyISkladniki",id).ToList();

            return View(xx);
        }
        public ActionResult Index4()
        {
            ListaXml lista = new ListaXml();
            var www = lista.Execute3();
            ViewBag.Liczba = www.Count(w => w.Nip == "brak");

            ViewBag.Liczba2 = www.Count();
            ViewBag.Liczba3 = www.Count(w => w.Opis.Contains("VB ELECTR"));

            return View(www);
        }
        // GET: Zamowienia

        public ActionResult Index()
        {
            List<PotrawyZamowieniaViewModel> potrawyZamowienia = new List<PotrawyZamowieniaViewModel>();


            List<PotrawyZamowieniaViewModel> potrawy = new List<PotrawyZamowieniaViewModel>();
            if (Session[ZamowieniaSesjaKlucz] != null)
                potrawyZamowienia = Session[ZamowieniaSesjaKlucz] as List<PotrawyZamowieniaViewModel>;
            //if (potrawyZamowienia.Count == 0)
            //{
            //    potrawyZamowienia.Add(new PotrawyZamowieniaViewModel { Ilosc = 2, KwotaRazem = 22, IdPotrawy=1, Cena = 22, Nazwa="dsfsd" });
            //    potrawyZamowienia.Add(new PotrawyZamowieniaViewModel { Ilosc = 4, KwotaRazem = 52, IdPotrawy=2, Cena = 11, Nazwa = "aaa" });
            //};
            potrawy = (from x in db.Potrawy
                       select new PotrawyZamowieniaViewModel
                       {
                           Ilosc = 0,
                           KwotaRazem = 0,
                           IdPotrawy = x.IdPotrawy,
                           Nazwa = x.Nazwa,
                           Cena = x.Cena
                       }).ToList();
            ViewBag.Razem = potrawyZamowienia.Sum(x => x.KwotaRazem);

            return View(potrawyZamowienia.Union(potrawy).DistinctBy(x => x.IdPotrawy).ToList());
        }
        // POST:  Potrawy/EdytujPotrawe/5
        [HttpPost]
        public ActionResult StatusZamowienia(List<PotrawyZamowieniaViewModel> listaZamowionychPotraw)
        {
            List<PotrawyZamowieniaViewModel> potrawyZamowienia = new List<PotrawyZamowieniaViewModel>();
            listaZamowionychPotraw.ForEach(x =>
            {
                if (x.Ilosc > 0) potrawyZamowienia.Add(new PotrawyZamowieniaViewModel
                {
                    IdPotrawy = x.IdPotrawy,
                    Ilosc = x.Ilosc,
                    KwotaRazem = x.Cena * x.Ilosc,
                    Cena = x.Cena,
                    Nazwa = x.Nazwa
                });
            }
            );
            Session[ZamowieniaSesjaKlucz] = potrawyZamowienia;
            return View(potrawyZamowienia);
        }

        [HttpPost]
        public ActionResult Wyslij(List<PotrawyZamowieniaViewModel> potrawyZamowienia, DateTime date)
        {
            Guid userId = new Guid(User.Identity.GetUserId());
            try
            {
                var Zamowienie = db.Zamowienia.Add(new Zamowienia { IdKlienta = userId, DataDodania = DateTime.Now, DataRealizacji = date });
                potrawyZamowienia.ForEach(w =>
                {
                    if (w.Ilosc > 0)
                    {
                        db.PozycjeZamowienia.Add(new PozycjeZamowienia { IdPotrawy = w.IdPotrawy, IdZamowienia = Zamowienie.IdZamowienia, Ilosc = w.Ilosc });
                    }
                });
                db.SaveChanges();
                ViewBag.CzyPoszlo = Zamowienie.IdZamowienia;
            }
            catch (Exception ex)
            {

                throw ex.InnerException.InnerException;
            }


            return View();
        }
        [HttpPost]
        public ActionResult DodajZamowienie(int idPotrawy, int iloscPotrawy)
        {


            List<PotrawyZamowieniaViewModel> potrawyZamowienia = new List<PotrawyZamowieniaViewModel>();
            if (Session[ZamowieniaSesjaKlucz] != null)
            {
                potrawyZamowienia = Session[ZamowieniaSesjaKlucz] as List<PotrawyZamowieniaViewModel>;
            }
            //Potrawy potrawy = db.Potrawy.FirstOrDefault(x => x.IdPotrawy == idPotrawy);
            //if (potrawy == null) return HttpNotFound();

            PotrawyZamowieniaViewModel nowaPozycja = new PotrawyZamowieniaViewModel()
            {
                Ilosc = iloscPotrawy,
                IdPotrawy = idPotrawy,
                KwotaRazem = iloscPotrawy
            };
            potrawyZamowienia.Add(nowaPozycja);

            Session[ZamowieniaSesjaKlucz] = potrawyZamowienia;
            return RedirectToAction("Index");
        }
    }
}

Views/Zamowienia/Index.cshtml
@model List<KlubSosnowy.Models.ViewModel.PotrawyZamowieniaViewModel>

@{
    ViewBag.Title = "Zamow Potrawy";

}

<h2>Zamow Potrawy</h2>

<table class="table">
    <tr>
        <th>
            IdPotrawy_skladnika
        </th>
        <th>
            NazwaSkladnika
        </th>
        <th>
            Cena
        </th>
        <th>
            Ilosc
        </th>
        <th>
            Suma
        </th>
    </tr>
    @using (Html.BeginForm("StatusZamowienia", "Zamowienia", FormMethod.Post))
    {
        for (var i = 0; i < Model.Count(); i++)
        {
            <tr>
                <td>
                    @Html.Hidden($"listaZamowionychPotraw[{@i}].IdPotrawy", Model[i].IdPotrawy.ToString())
                    @Html.Hidden($"listaZamowionychPotraw[{@i}].Nazwa", Model[i].Nazwa)
                    @Html.Hidden($"listaZamowionychPotraw[{@i}].Cena", Model[i].Cena,new { @class = "cena" + i })

                    @Html.Label(Model[i].IdPotrawy.ToString(), new { id = $"listaZamowionychPotraw[{@i}].IdPotrawy" })
                </td>
                <td>
                    @Html.Label(Model[i].Nazwa, new { id = Model[i].Nazwa })
                </td>
                <td>
                    @Html.Raw(Model[i].Cena)
                </td>
                <td>
                    @Html.TextBox("listaZamowionychPotraw[" + @i + "].Ilosc", Model[i].Ilosc,new { @class = "ilosc", id="ilosc" + i })
                </td>
                <td>
                    @Html.Label(Model[i].KwotaRazem.ToString(), new { id = Model[i].KwotaRazem ,@class="kwotaRazem"+i})

                </td>
            </tr>
        }
        <tr>
            <td colspan="4">
                Suma wszystkich pozycji:
            </td>
            <td id="suma">
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <input type="submit" value="Submit" />
            </td>
        </tr>
    }
</table>
<p>Name: <input type="text" name="user"></p>

<button>Set the value of the input field</button>

<script>
$(".ilosc").on("change", function () {
        obliczKwote();
    });
    function obliczKwote() {
        var suma = 0;
        for (var i = 0; i < @Model.Count(); i++) {
            var ile = parseFloat($("#ilosc"+i).val());
            var cena = parseFloat($(".cena"+i).val());
            var razem = ile * cena;
            suma += razem;
            $("#suma").html(suma);
            $(".kwotaRazem"+i).html(razem);
        }
    }
</script>

Views/Zamowienia/Index4.cshtml
@model IEnumerable<KlubSosnowy.Models.ViewModel.BankWithNip>

@{
    ViewBag.Title = "List z Xml";
}

<h2>List z Xml @ViewBag.Liczba / @ViewBag.Liczba2</h2>
<h2>platnosc karta @ViewBag.Liczba3</h2>
<table class="table">
    <tr>
        <th>
            T
        </th>
        <th>
            Data
        </th>
        <th>
            Nazwa
        </th>
        <th>
            Tytułem
        </th>
        <th>
            Opis
        </th>
        <th>
            Wyplata w PLN
        </th>
        <th>
            Nip
        </th>
        <th>
            id
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.T)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tytulem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WyplataWPln)
            </td>
                        <td>
                @Html.DisplayFor(modelItem => item.Nip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
        </tr>
    }

</table>

Views/Zamowienia/StatusZamowienia.cshtml
@model List<KlubSosnowy.Models.ViewModel.PotrawyZamowieniaViewModel>

@{
    ViewBag.Title = "Zamow Potrawy";

}

<h2>Zamow Potrawy</h2>

<table class="table">
    <tr>
        <th>
            IdPotrawy_skladnika
        </th>
        <th>
            NazwaSkladnika
        </th>
        <th>
            Cena
        </th>
        <th>
            Ilosc
        </th>
        <th>
            Suma
        </th>
    </tr>
    @using (Html.BeginForm("Wyslij", "Zamowienia", FormMethod.Post))
    {
        for (var i = 0; i < Model.Count(); i++)
        {
            <tr>
                <td>
                    @Html.Hidden($"potrawyZamowienia[{@i}].IdPotrawy", Model[i].IdPotrawy.ToString())
                    @Html.Hidden($"potrawyZamowienia[{@i}].Nazwa", Model[i].Nazwa)
                    @Html.Hidden($"potrawyZamowienia[{@i}].Cena", Model[i].Cena, new { @class = "cena" + Model[i].IdPotrawy.ToString() })

                    @Html.Label(Model[i].IdPotrawy.ToString(), new { id = $"listaZamowionychPotraw[{@i}].IdPotrawy" })
                </td>
                <td>
                    @Html.Label(Model[i].Nazwa, new { id = Model[i].Nazwa })
                </td>
                <td>
                    @Html.Raw(Model[i].Cena)
                </td>
                <td>
                    @Html.TextBox("potrawyZamowienia[" + @i + "].Ilosc", Model[i].Ilosc, new { @class = "ilosc", id = "ilosc" + Model[i].IdPotrawy.ToString() })
                </td>
                <td>
                    @Html.Label(Model[i].KwotaRazem.ToString(), new { id = Model[i].KwotaRazem, @class = "kwotaRazem" + Model[i].IdPotrawy.ToString() })
                </td>
            </tr>
        }
        <tr>
            <td colspan="4">
                Suma wszystkich pozycji:
            </td>
            <td id="suma">
            </td>
        </tr>
        <tr>
            <td>
                <input asp-for="BestellungsDatum" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control" name="date"/>
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <input type="submit" value="Submit" class="btn-primary btn"/>
            </td>
        </tr>
    }
</table>
<script>
    //obliczKwote();
$(".ilosc").on("change", function () {
        obliczKwote();
    });
    function obliczKwote() {
        var suma = 0;
        var model =@Html.Raw(Json.Encode(Model));
        console.log(model);
        for(var i = 0; i < model.length; i++) {
            var ile = parseFloat($("#ilosc" + model[i].IdPotrawy).val());
            var cena = parseFloat($(".cena" + model[i].IdPotrawy).val());
            console.log(ile);
            console.log(cena);
            var razem = ile * cena;
            suma += razem;
            $("#suma").html(suma);
            $(".kwotaRazem" + model[i].IdPotrawy).html(razem);
        }
    }
</script>

Views/Zamowienia/Wyslij.cshtml
@{
    ViewBag.Title = "Wyslano";

}

<h2>Zamowienie o nr @ViewBag.CzyPoszlo zostało wysłane</h2>